export const LEAGUES = {
  br: [
    { id: "abs_br_1", name: "Atlético Mineiro", ovr: 81 },
    { id: "abs_br_2", name: "Grêmio", ovr: 80 },
    { id: "abs_br_3", name: "Internacional", ovr: 79 },
    { id: "abs_br_4", name: "Fluminense", ovr: 79 },
    { id: "abs_br_5", name: "Botafogo", ovr: 78 },
    { id: "abs_br_6", name: "Athletico-PR", ovr: 78 },
    { id: "abs_br_7", name: "Cruzeiro", ovr: 77 },
    { id: "abs_br_8", name: "Fortaleza", ovr: 77 },
    { id: "abs_br_9", name: "Bahia", ovr: 76 },
    { id: "abs_br_10", name: "Vitória", ovr: 75 },
    { id: "abs_br_11", name: "Coritiba", ovr: 74 },
    { id: "abs_br_12", name: "Goiás", ovr: 73 },
    { id: "abs_br_13", name: "Criciúma", ovr: 72 },
    { id: "abs_br_14", name: "Sport Recife", ovr: 72 },
    { id: "abs_br_15", name: "Ceará", ovr: 71 },
    { id: "abs_br_16", name: "Juventude", ovr: 70 },
    { id: "abs_br_17", name: "Bragantino", ovr: 76 },
    { id: "abs_br_18", name: "Santos", ovr: 75 },
    { id: "abs_br_19", name: "Ponte Preta", ovr: 71 },
  ],
  en: [
    { id: "abs_en_1", name: "Arsenal", ovr: 85 },
    { id: "abs_en_2", name: "Liverpool", ovr: 84 },
    { id: "abs_en_3", name: "Chelsea", ovr: 83 },
    { id: "abs_en_4", name: "Tottenham", ovr: 82 },
    { id: "abs_en_5", name: "Aston Villa", ovr: 81 },
    { id: "abs_en_6", name: "Newcastle", ovr: 81 },
    { id: "abs_en_7", name: "West Ham", ovr: 80 },
    { id: "abs_en_8", name: "Brighton", ovr: 79 },
    { id: "abs_en_9", name: "Fulham", ovr: 78 },
    { id: "abs_en_10", name: "Crystal Palace", ovr: 77 },
    { id: "abs_en_11", name: "Brentford", ovr: 77 },
    { id: "abs_en_12", name: "Bournemouth", ovr: 76 },
    { id: "abs_en_13", name: "Nottingham Forest", ovr: 76 },
    { id: "abs_en_14", name: "Everton", ovr: 76 },
    { id: "abs_en_15", name: "Wolverhampton", ovr: 75 },
    { id: "abs_en_16", name: "Leicester", ovr: 75 },
    { id: "abs_en_17", name: "Southampton", ovr: 74 },
    { id: "abs_en_18", name: "Ipswich Town", ovr: 73 },
    { id: "abs_en_19", name: "Leeds United", ovr: 73 },
  ],
  es: [
    { id: "abs_es_1", name: "Atlético Madrid", ovr: 84 },
    { id: "abs_es_2", name: "Girona", ovr: 81 },
    { id: "abs_es_3", name: "Real Sociedad", ovr: 81 },
    { id: "abs_es_4", name: "Athletic Club", ovr: 80 },
    { id: "abs_es_5", name: "Real Betis", ovr: 80 },
    { id: "abs_es_6", name: "Villarreal", ovr: 79 },
    { id: "abs_es_7", name: "Valencia", ovr: 79 },
    { id: "abs_es_8", name: "Sevilla", ovr: 78 },
    { id: "abs_es_9", name: "Celta Vigo", ovr: 77 },
    { id: "abs_es_10", name: "Osasuna", ovr: 77 },
    { id: "abs_es_11", name: "Getafe", ovr: 76 },
    { id: "abs_es_12", name: "Mallorca", ovr: 76 },
    { id: "abs_es_13", name: "Alavés", ovr: 75 },
    { id: "abs_es_14", name: "Rayo Vallecano", ovr: 75 },
    { id: "abs_es_15", name: "Las Palmas", ovr: 75 },
    { id: "abs_es_16", name: "Leganés", ovr: 74 },
    { id: "abs_es_17", name: "Valladolid", ovr: 74 },
    { id: "abs_es_18", name: "Espanyol", ovr: 73 },
    { id: "abs_es_19", name: "Granada", ovr: 73 },
  ],
  it: [
    { id: "abs_it_1", name: "Inter Milan", ovr: 85 },
    { id: "abs_it_2", name: "Juventus", ovr: 84 },
    { id: "abs_it_3", name: "AC Milan", ovr: 84 },
    { id: "abs_it_4", name: "Napoli", ovr: 83 },
    { id: "abs_it_5", name: "Roma", ovr: 82 },
    { id: "abs_it_6", name: "Atalanta", ovr: 82 },
    { id: "abs_it_7", name: "Lazio", ovr: 81 },
    { id: "abs_it_8", name: "Fiorentina", ovr: 80 },
    { id: "abs_it_9", name: "Bologna", ovr: 79 },
    { id: "abs_it_10", name: "Torino", ovr: 78 },
    { id: "abs_it_11", name: "Monza", ovr: 77 },
    { id: "abs_it_12", name: "Genoa", ovr: 77 },
    { id: "abs_it_13", name: "Lecce", ovr: 76 },
    { id: "abs_it_14", name: "Empoli", ovr: 76 },
    { id: "abs_it_15", name: "Udinese", ovr: 75 },
    { id: "abs_it_16", name: "Hellas Verona", ovr: 75 },
    { id: "abs_it_17", name: "Cagliari", ovr: 74 },
    { id: "abs_it_18", name: "Como", ovr: 74 },
    { id: "abs_it_19", name: "Parma", ovr: 73 },
  ],
  de: [
    { id: "abs_de_1", name: "Bayer Leverkusen", ovr: 85 },
    { id: "abs_de_2", name: "Borussia Dortmund", ovr: 84 },
    { id: "abs_de_3", name: "RB Leipzig", ovr: 83 },
    { id: "abs_de_4", name: "VfB Stuttgart", ovr: 82 },
    { id: "abs_de_5", name: "Eintracht Frankfurt", ovr: 81 },
    { id: "abs_de_6", name: "Freiburg", ovr: 79 },
    { id: "abs_de_7", name: "Wolfsburg", ovr: 78 },
    { id: "abs_de_8", name: "Hoffenheim", ovr: 78 },
    { id: "abs_de_9", name: "Werder Bremen", ovr: 77 },
    { id: "abs_de_10", name: "B. M'gladbach", ovr: 77 },
    { id: "abs_de_11", name: "Augsburg", ovr: 76 },
    { id: "abs_de_12", name: "Mainz 05", ovr: 76 },
    { id: "abs_de_13", name: "Union Berlin", ovr: 75 },
    { id: "abs_de_14", name: "Bochum", ovr: 75 },
    { id: "abs_de_15", name: "Heidenheim", ovr: 74 },
    { id: "abs_de_16", name: "St. Pauli", ovr: 73 },
    { id: "abs_de_17", name: "Holstein Kiel", ovr: 73 },
  ],
};
